- hosts: hosts-with-tpm2
  collections:
    - whooo.tpm2
  tasks:
    - name: validate ECC ek
      tpm2_validate_ek:
        type: 'ecc'
        capath: 'tpm2-ca.pem'
        crlpath: 'tpm2-crl.pem'
        template_path: "ek/{{ ansible_fqdn }}-ecc-template"
        public_path: "ek/{{ ansible_fqdn }}-ecc-public"
    - name: create ECC ak
      tpm2_create_ak:
        type: 'ecc'
        ek_template: "ek/{{ ansible_fqdn }}-ecc-template"
        ek_public: "ek/{{ ansible_fqdn }}-ecc-public"
        ak: "ak/{{ ansible_fqdn }}-ecc.json"
    - name: create RSA ak
      tpm2_create_ak:
        type: 'rsa'
        ek_template: "ek/{{ ansible_fqdn }}-ecc-template"
        ek_public: "ek/{{ ansible_fqdn }}-ecc-public"
        ak: "ak/{{ ansible_fqdn }}-rsa.json"
    - name: quote
      tpm2_quote:
        ak: "ak/{{ ansible_fqdn }}-ecc.json"
